apiVersion: appstudio.redhat.com/v1beta2
kind: IntegrationTestScenario
metadata:
  labels:
    test.appstudio.openshift.io/optional: "false"
  name: odh-olminstall-smoke
  namespace: open-data-hub-tenant
  annotations:
    openshift.io/description: >
      FBCF olminstall smoke for opendatahub-builds. For rhoai-tenant or other apps, duplicate this ITS with
      updated namespace/application/contexts after stakeholder alignment (see README).
spec:
  application: opendatahub-builds
  contexts:
    - description: Execute olminstall smoke test when FBCF (odh-operator-catalog) is built
      name: component_odh-operator-catalog
  resolverRef:
    params:
      - name: url
        value: https://github.com/opendatahub-io/odh-konflux-central.git
      - name: revision
        value: main
      - name: pathInRepo
        value: integration-tests/olminstall/olminstall-smoke-pipeline.yaml
    resolver: git
    resourceKind: pipeline
