FROM registry.access.redhat.com/ubi9/go-toolset

USER 0:0

RUN dnf install -y \
    jq \
    wget \
    tar \
    && dnf clean all

RUN wget https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-client-linux.tar.gz && \
    tar xvf openshift-client-linux.tar.gz && \
    chmod +x oc kubectl && \
    mv oc /usr/local/bin/ && \
    mv kubectl /usr/local/bin/ && \
    rm -f openshift-client-linux.tar.gz

RUN go install gotest.tools/gotestsum@v1.13.0 && \
    mv /opt/app-root/src/go/bin/gotestsum /usr/local/bin/gotestsum
