FROM registry.access.redhat.com/ubi9/ubi
RUN dnf install -y --nodocs make git golang jq python3.9 python3-pip wget
RUN pip3.9 install --upgrade pip
RUN wget https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-client-linux.tar.gz && \
    tar xvf openshift-client-linux.tar.gz && chmod +x oc && mv oc /usr/local/bin/ && chmod +x kubectl && mv kubectl /usr/local/bin/