config:
  default-branches-allowlist:
    - main
    - master
  repositories:
    # additional-branches: []
    #  early-gate-required-on-default-branches: false
    kserve:
      early-gate-enabled: true
      additional-branches:
        - release-v0.17
    data-science-pipelines-operator:
      early-gate-enabled: true
      additional-branches:
        - earlygate-test
      
    model-registry:
      early-gate-enabled: true
