FROM registry.access.redhat.com/ubi9/go-toolset:1.25.7-1772454089
User 0
RUN yum install -y git jq wget tar python3 pip podman skopeo make gcc automake binutils && \
    yum clean all && rm -rf /var/cache/dnf/*
RUN wget https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-client-linux.tar.gz && \
    tar xvf openshift-client-linux.tar.gz && chmod +x oc && mv oc /usr/local/bin/
RUN ln -s /usr/local/bin/oc /usr/bin/kubectl