FROM registry.access.redhat.com/ubi9/python-311:1-1779945715

USER 0:0
RUN dnf install -y jq
RUN wget https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-client-linux.tar.gz && \
    tar xvf openshift-client-linux.tar.gz && chmod +x oc && mv oc /usr/local/bin/ && chmod +x kubectl && mv kubectl /usr/local/bin/
WORKDIR /go

ENV BASH_ENV="" ENV="" PROMPT_COMMAND=""
