---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/opendatahub-io/kserve?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
    pipelinesascode.tekton.dev/on-comment: "^/post-release-smoke\\s+\\S+"
  name: kserve-post-release-smoke
  namespace: open-data-hub-tenant
  labels:
    appstudio.openshift.io/application: group-testing
    appstudio.openshift.io/component: kserve-group
    pipelines.appstudio.openshift.io/type: test
spec:
  params:
    - name: release_tag
      value: ""
    - name: trigger_comment
      value: "{{ trigger_comment }}"
    - name: operator_image
      value: ""
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: https://github.com/opendatahub-io/odh-konflux-central.git
      - name: revision
        value: main
      - name: pathInRepo
        value: integration-tests/kserve/post-release-smoke-pipeline.yaml
  taskRunTemplate:
    podTemplate:
      nodeSelector:
        konflux-ci.dev/workload: konflux-tenants
      tolerations:
        - effect: NoSchedule
          key: konflux-ci.dev/workload
          operator: Equal
          value: konflux-tenants
    serviceAccountName: konflux-integration-runner
