FROM registry.access.redhat.com/ubi9/go-toolset

USER 0:0

RUN dnf install -y \
    git \
    make \
    jq \
    wget \
    tar \
    && dnf clean all

RUN wget https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-client-linux.tar.gz && \
    tar xvf openshift-client-linux.tar.gz && chmod +x oc && mv oc /usr/local/bin/
