FROM registry.access.redhat.com/ubi9/go-toolset

USER 0:0

RUN dnf install -y \
    git \
    make \
    jq \
    wget \
    tar \
    python3 \
    python3-pip \
    && dnf clean all

RUN wget https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-client-linux.tar.gz && \
    tar xvf openshift-client-linux.tar.gz && chmod +x oc kubectl && mv oc kubectl /usr/local/bin/

RUN GOBIN=/usr/local/bin go install gotest.tools/gotestsum@v1.13.0

RUN python3 -m pip install --no-cache-dir --disable-pip-version-check junitparser==4.0.2
